[package]
name = "work"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
clap = { version = "4", features = ["derive"] }
colored = "3.1.1"
dirs = "6.0.0"
tempfile = "3.24.0"

[[bin]]
name = "tag"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
